# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

# 对于我们使用cocoapod引入的第三方,我们可以在podfile文件中 增加一句  inhibit_all_warnings! 来要pod的工程不显示任何警告
inhibit_all_warnings!

target 'DayYue' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for DayYue
    
    pod 'PureLayout', '~> 3.0.2'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 4.0.0'
    pod 'Masonry', '~> 1.0.2'
    pod 'MJExtension', '~> 3.0.13'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'SVProgressHUD', '~> 2.1.2'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'BlocksKit', '~> 2.2.5'
    
end
